// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// awat Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1QODLyN4ARB3JDdCiIQc8VUJse8Arjhs',
    appId: '1:49670848283:web:ec44a18521ba407ad0ddbe',
    messagingSenderId: '49670848283',
    projectId: 'mascotas-app-vldv',
    authDomain: 'mascotas-app-vldv.firebaseapp.com',
    storageBucket: 'mascotas-app-vldv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOfMzcGXzWdoeDHiPKGod83IlFV7gCws',
    appId: '1:49670848283:android:4ba20f454e06ccbfd0ddbe',
    messagingSenderId: '49670848283',
    projectId: 'mascotas-app-vldv',
    storageBucket: 'mascotas-app-vldv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIeh5IiHVtXcPacB7M5tQA_sNbeD3AHo',
    appId: '1:49670848283:ios:6b2f35b4d7f2043fd0ddbe',
    messagingSenderId: '49670848283',
    projectId: 'mascotas-app-vldv',
    storageBucket: 'mascotas-app-vldv.firebasestorage.app',
    iosBundleId: 'com.example.appMascotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQIeh5IiHVtXcPacB7M5tQA_sNbeD3AHo',
    appId: '1:49670848283:ios:6b2f35b4d7f2043fd0ddbe',
    messagingSenderId: '49670848283',
    projectId: 'mascotas-app-vldv',
    storageBucket: 'mascotas-app-vldv.firebasestorage.app',
    iosBundleId: 'com.example.appMascotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1QODLyN4ARB3JDdCiIQc8VUJse8Arjhs',
    appId: '1:49670848283:web:bd25a305a586c3a9d0ddbe',
    messagingSenderId: '49670848283',
    projectId: 'mascotas-app-vldv',
    authDomain: 'mascotas-app-vldv.firebaseapp.com',
    storageBucket: 'mascotas-app-vldv.firebasestorage.app',
  );
}
